name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v4.0.0
      - uses: gradle/gradle-build-action@v2.10.0
        with:
          arguments: clean build
      - name: Run a one-line script
        run: java -jar ./build/libs/advent-of-code-2023-1.0-SNAPSHOT-all.jar akk
