name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check project sources
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.10.0
      - name: Run Gradle
        run: ./gradlew clean build
      - name: Execute Advent of Code puzzle solver
        run: java -jar ./build/libs/advent-of-code-2023-1.0-SNAPSHOT-all.jar akk
